-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 22:30:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sfcs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sfcs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sfcs` DEFAULT CHARACTER SET utf8 ;
USE `db_sfcs` ;

-- -----------------------------------------------------
-- Table `db_sfcs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sfcs`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `usertype` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE USER 'sfcs_user' IDENTIFIED BY 'sfcs_password';

GRANT SELECT ON TABLE `db_sfcs`.* TO 'sfcs_user';
GRANT SELECT, INSERT, TRIGGER ON TABLE `db_sfcs`.* TO 'sfcs_user';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `db_sfcs`.* TO 'sfcs_user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
